import type { Customer, Asset, AIAnalysis, SupportTicket, DashboardMetrics, KnowledgeArticle } from '@/types';

// Mock data store — replace with Supabase queries when backend is connected

export const mockCustomers: Customer[] = [
  {
    id: 'c1',
    name: 'Dr. Sarah Chen',
    email: 'sarah.chen@medtech-solutions.com',
    phone: '+1 (415) 555-0192',
    company: 'MedTech Solutions GmbH',
    industry: 'Medical Technology',
    country: 'Germany',
    city: 'Munich',
    status: 'active',
    tier: 'enterprise',
    assetCount: 12,
    openTickets: 2,
    contractStart: '2023-01-01',
    contractEnd: '2025-12-31',
    createdAt: '2023-01-01T09:00:00Z',
    updatedAt: '2024-11-15T14:30:00Z',
  },
  {
    id: 'c2',
    name: 'Prof. James Morrison',
    email: 'j.morrison@stanford-research.edu',
    phone: '+1 (650) 555-0847',
    company: 'Stanford Research Institute',
    industry: 'Academic Research',
    country: 'USA',
    city: 'Palo Alto',
    status: 'active',
    tier: 'enterprise',
    assetCount: 8,
    openTickets: 1,
    contractStart: '2022-06-15',
    contractEnd: '2026-06-14',
    createdAt: '2022-06-15T10:00:00Z',
    updatedAt: '2024-12-01T09:15:00Z',
  },
  {
    id: 'c3',
    name: 'Yuki Tanaka',
    email: 'y.tanaka@semiconductor-advanced.jp',
    phone: '+81 3-5555-0234',
    company: 'Advanced Semiconductor Corp',
    industry: 'Semiconductor',
    country: 'Japan',
    city: 'Tokyo',
    status: 'active',
    tier: 'enterprise',
    assetCount: 24,
    openTickets: 5,
    contractStart: '2021-04-01',
    contractEnd: '2025-03-31',
    createdAt: '2021-04-01T08:00:00Z',
    updatedAt: '2024-12-10T16:45:00Z',
  },
  {
    id: 'c4',
    name: 'Lena Müller',
    email: 'l.mueller@optik-precision.de',
    phone: '+49 89 555-0381',
    company: 'Optik Precision Systems',
    industry: 'Industrial Metrology',
    country: 'Germany',
    city: 'Oberkochen',
    status: 'active',
    tier: 'business',
    assetCount: 6,
    openTickets: 0,
    contractStart: '2023-07-01',
    contractEnd: '2024-12-31',
    createdAt: '2023-07-01T11:00:00Z',
    updatedAt: '2024-11-20T13:00:00Z',
  },
  {
    id: 'c5',
    name: 'Dr. Ahmed Hassan',
    email: 'a.hassan@cairo-eyecenter.eg',
    phone: '+20 2 555-0567',
    company: 'Cairo Eye Center',
    industry: 'Ophthalmology',
    country: 'Egypt',
    city: 'Cairo',
    status: 'active',
    tier: 'business',
    assetCount: 4,
    openTickets: 1,
    contractStart: '2024-01-15',
    contractEnd: '2025-01-14',
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-12-05T12:00:00Z',
  },
  {
    id: 'c6',
    name: 'Maria Rodriguez',
    email: 'm.rodriguez@semiconductor-tech.es',
    phone: '+34 91 555-0729',
    company: 'SemTech Iberia',
    industry: 'Semiconductor',
    country: 'Spain',
    city: 'Madrid',
    status: 'pending',
    tier: 'starter',
    assetCount: 2,
    openTickets: 0,
    contractStart: '2024-12-01',
    contractEnd: '2025-11-30',
    createdAt: '2024-12-01T09:00:00Z',
    updatedAt: '2024-12-01T09:00:00Z',
  },
];

export const mockAssets: Asset[] = [
  {
    id: 'a1',
    customerId: 'c1',
    customerName: 'MedTech Solutions GmbH',
    name: 'ZEISS Axio Observer 7',
    category: 'Microscopy',
    modelNumber: 'AO7-2023-PRO',
    serialNumber: 'ZSS-AO7-00391',
    purchaseDate: '2021-03-15',
    warrantyExpiry: '2024-03-14',
    usageHours: 8420,
    condition: 'fair',
    lastMaintenance: '2024-09-10',
    nextMaintenanceDue: '2025-03-10',
    issueDescription: 'Intermittent autofocus failure at 100x magnification. Objective turret shows slight resistance during rotation.',
    location: 'Lab 3A, Munich HQ',
    firmware: 'v4.2.1',
    status: 'warning',
    createdAt: '2021-03-15T10:00:00Z',
    updatedAt: '2024-12-10T09:00:00Z',
  },
  {
    id: 'a2',
    customerId: 'c1',
    customerName: 'MedTech Solutions GmbH',
    name: 'ZEISS CIRRUS HD-OCT 6000',
    category: 'Ophthalmology',
    modelNumber: 'OCT6000-HD',
    serialNumber: 'ZSS-OCT-00847',
    purchaseDate: '2022-08-20',
    warrantyExpiry: '2025-08-19',
    usageHours: 3240,
    condition: 'good',
    lastMaintenance: '2024-11-05',
    nextMaintenanceDue: '2025-05-05',
    location: 'Clinic Wing B',
    firmware: 'v3.1.0',
    status: 'operational',
    createdAt: '2022-08-20T10:00:00Z',
    updatedAt: '2024-11-05T11:00:00Z',
  },
  {
    id: 'a3',
    customerId: 'c3',
    customerName: 'Advanced Semiconductor Corp',
    name: 'ZEISS SIGMA 500 SEM',
    category: 'Semiconductor',
    modelNumber: 'SIGMA500-FE',
    serialNumber: 'ZSS-SEM-01204',
    purchaseDate: '2020-11-01',
    warrantyExpiry: '2023-10-31',
    usageHours: 14800,
    condition: 'poor',
    lastMaintenance: '2024-07-20',
    nextMaintenanceDue: '2025-01-20',
    issueDescription: 'Detector sensitivity declining. Vacuum pump showing elevated noise levels. Secondary electron detector calibration required.',
    location: 'Clean Room Floor 2',
    firmware: 'v2.8.4',
    status: 'warning',
    createdAt: '2020-11-01T09:00:00Z',
    updatedAt: '2024-12-08T14:30:00Z',
  },
  {
    id: 'a4',
    customerId: 'c2',
    customerName: 'Stanford Research Institute',
    name: 'ZEISS LSM 980 Confocal',
    category: 'Research Systems',
    modelNumber: 'LSM980-CFS',
    serialNumber: 'ZSS-LSM-00673',
    purchaseDate: '2023-02-10',
    warrantyExpiry: '2026-02-09',
    usageHours: 2100,
    condition: 'excellent',
    lastMaintenance: '2024-10-15',
    nextMaintenanceDue: '2025-04-15',
    location: 'Bio-imaging Center, Room 215',
    firmware: 'v5.0.2',
    status: 'operational',
    createdAt: '2023-02-10T09:00:00Z',
    updatedAt: '2024-10-15T10:00:00Z',
  },
  {
    id: 'a5',
    customerId: 'c3',
    customerName: 'Advanced Semiconductor Corp',
    name: 'ZEISS GeminiSEM 560',
    category: 'Semiconductor',
    modelNumber: 'GEMINI560-PLUS',
    serialNumber: 'ZSS-GSEM-00289',
    purchaseDate: '2019-06-01',
    warrantyExpiry: '2022-05-31',
    usageHours: 22400,
    condition: 'critical',
    lastMaintenance: '2024-06-15',
    nextMaintenanceDue: '2024-12-15',
    issueDescription: 'Critical: Field emission gun showing voltage instability. Stage controller firmware outdated. Multiple sensor failures detected.',
    location: 'Semiconductor Lab A1',
    firmware: 'v1.9.2',
    status: 'maintenance',
    createdAt: '2019-06-01T09:00:00Z',
    updatedAt: '2024-12-01T08:00:00Z',
  },
  {
    id: 'a6',
    customerId: 'c4',
    customerName: 'Optik Precision Systems',
    name: 'ZEISS O-INSPECT 543',
    category: 'Industrial Metrology',
    modelNumber: 'OINSPECT-543',
    serialNumber: 'ZSS-OIM-00156',
    purchaseDate: '2022-04-20',
    warrantyExpiry: '2025-04-19',
    usageHours: 4600,
    condition: 'good',
    lastMaintenance: '2024-08-30',
    nextMaintenanceDue: '2025-02-28',
    location: 'QC Department, Station 4',
    firmware: 'v3.3.1',
    status: 'operational',
    createdAt: '2022-04-20T09:00:00Z',
    updatedAt: '2024-08-30T12:00:00Z',
  },
];

export const mockAnalyses: AIAnalysis[] = [
  {
    id: 'ai1',
    assetId: 'a1',
    assetName: 'ZEISS Axio Observer 7',
    customerId: 'c1',
    customerName: 'MedTech Solutions GmbH',
    riskScore: 72,
    riskLevel: 'high',
    priority: 'high',
    rootCause: 'Mechanical wear detected in objective turret rotation mechanism. Autofocus piezo actuator showing 23% degradation from baseline calibration. Extended operation at high cycle rates has accelerated bearing wear.',
    recommendation: 'Schedule preventive maintenance within 30 days. Replace objective turret bearing assembly. Recalibrate autofocus system. Consider upgrading to latest firmware v4.3.0 which includes improved autofocus algorithms.',
    estimatedDowntime: '4-6 hours',
    suggestedAction: 'Schedule Preventive Maintenance',
    confidence: 87,
    components: [
      { name: 'Objective Turret', health: 52, status: 'degraded', notes: 'Bearing wear detected' },
      { name: 'Autofocus System', health: 45, status: 'degraded', notes: 'Piezo actuator degradation' },
      { name: 'Illumination System', health: 91, status: 'healthy', notes: 'Operating normally' },
      { name: 'Camera Interface', health: 88, status: 'healthy', notes: 'Within spec' },
    ],
    actionItems: [
      { id: 'act1', action: 'Replace objective turret bearing assembly', priority: 'high', estimatedTime: '2 hours', cost: '€320', completed: false },
      { id: 'act2', action: 'Recalibrate autofocus piezo actuator', priority: 'high', estimatedTime: '1.5 hours', cost: '€180', completed: false },
      { id: 'act3', action: 'Update firmware to v4.3.0', priority: 'medium', estimatedTime: '30 min', cost: 'Included', completed: false },
      { id: 'act4', action: 'Clean optical path and objective lenses', priority: 'low', estimatedTime: '1 hour', cost: '€60', completed: false },
    ],
    analyzedAt: '2024-12-10T14:35:00Z',
    model: 'gemini-2.0-flash',
  },
  {
    id: 'ai2',
    assetId: 'a5',
    assetName: 'ZEISS GeminiSEM 560',
    customerId: 'c3',
    customerName: 'Advanced Semiconductor Corp',
    riskScore: 94,
    riskLevel: 'critical',
    priority: 'critical',
    rootCause: 'Field emission gun voltage instability indicating cathode degradation (22,400 hours operation, well past 15,000h recommended replacement). Stage controller using firmware 3 versions behind. Multiple thermal sensors reporting out-of-spec readings suggesting cooling system inefficiency.',
    recommendation: 'IMMEDIATE ACTION REQUIRED. The asset poses significant risk of complete failure within 2-4 weeks. Arrange emergency maintenance. FEG cathode replacement is critical. Do not operate at high beam currents until serviced.',
    estimatedDowntime: '2-3 days',
    suggestedAction: 'Emergency Maintenance Required',
    confidence: 96,
    components: [
      { name: 'Field Emission Gun', health: 15, status: 'critical', notes: 'Cathode nearing end of life' },
      { name: 'Stage Controller', health: 41, status: 'degraded', notes: 'Outdated firmware' },
      { name: 'Cooling System', health: 58, status: 'degraded', notes: 'Efficiency below threshold' },
      { name: 'Detector Array', health: 34, status: 'degraded', notes: 'Multiple sensor failures' },
    ],
    actionItems: [
      { id: 'act5', action: 'Replace FEG cathode immediately', priority: 'critical', estimatedTime: '8 hours', cost: '¥280,000', completed: false },
      { id: 'act6', action: 'Update stage controller firmware', priority: 'high', estimatedTime: '2 hours', cost: 'Included', completed: false },
      { id: 'act7', action: 'Service cooling system', priority: 'high', estimatedTime: '4 hours', cost: '¥45,000', completed: false },
      { id: 'act8', action: 'Replace failed detector sensors', priority: 'medium', estimatedTime: '3 hours', cost: '¥65,000', completed: false },
    ],
    analyzedAt: '2024-12-10T11:20:00Z',
    model: 'gemini-2.0-flash',
  },
  {
    id: 'ai3',
    assetId: 'a3',
    assetName: 'ZEISS SIGMA 500 SEM',
    customerId: 'c3',
    customerName: 'Advanced Semiconductor Corp',
    riskScore: 68,
    riskLevel: 'high',
    priority: 'high',
    rootCause: 'Vacuum pump acoustic signature analysis indicates impeller wear consistent with 14,800 operational hours. Secondary electron detector response curve showing 18% sensitivity reduction from initial baseline. Turbo pump bearing temperature elevated by 12°C above nominal.',
    recommendation: 'Schedule maintenance within 45 days. Replace turbo pump assembly. Recalibrate SE detector. Clean and inspect complete vacuum system. Consider upgrading vacuum controller firmware for improved diagnostics.',
    estimatedDowntime: '1-2 days',
    suggestedAction: 'Schedule Maintenance',
    confidence: 82,
    components: [
      { name: 'Vacuum System', health: 48, status: 'degraded', notes: 'Pump wear detected' },
      { name: 'SE Detector', health: 62, status: 'degraded', notes: 'Sensitivity reduced' },
      { name: 'Electron Column', health: 79, status: 'healthy', notes: 'Within acceptable range' },
      { name: 'Stage System', health: 85, status: 'healthy', notes: 'Operating normally' },
    ],
    actionItems: [
      { id: 'act9', action: 'Replace turbo pump assembly', priority: 'high', estimatedTime: '6 hours', cost: '¥120,000', completed: false },
      { id: 'act10', action: 'Recalibrate SE detector', priority: 'medium', estimatedTime: '2 hours', cost: '¥30,000', completed: false },
      { id: 'act11', action: 'Full vacuum system service', priority: 'medium', estimatedTime: '4 hours', cost: '¥55,000', completed: false },
    ],
    analyzedAt: '2024-12-09T16:10:00Z',
    model: 'gemini-2.0-flash',
  },
];

export const mockTickets: SupportTicket[] = [
  {
    id: 't1',
    title: 'Autofocus failure at high magnification - Axio Observer 7',
    description: 'Customer reports intermittent autofocus failure when operating at 100x magnification. Issue occurs approximately every 15-20 samples and requires manual refocus.',
    status: 'in_progress',
    priority: 'high',
    customerId: 'c1',
    customerName: 'MedTech Solutions GmbH',
    assetId: 'a1',
    assetName: 'ZEISS Axio Observer 7',
    assignedTo: 'eng1',
    assignedEngineer: 'Thomas Weber',
    createdAt: '2024-12-08T10:30:00Z',
    updatedAt: '2024-12-10T14:00:00Z',
    dueDate: '2024-12-20T17:00:00Z',
    tags: ['autofocus', 'microscopy', 'hardware'],
    comments: [
      {
        id: 'cm1',
        authorId: 'eng1',
        authorName: 'Thomas Weber',
        content: 'I have reviewed the diagnostic logs. The autofocus piezo actuator shows clear degradation. Scheduling on-site visit for Dec 15.',
        createdAt: '2024-12-09T09:00:00Z',
        isInternal: false,
      },
    ],
  },
  {
    id: 't2',
    title: 'CRITICAL: FEG voltage instability - GeminiSEM 560',
    description: 'Field emission gun showing critical voltage fluctuations. AI analysis indicates cathode near end of life. Risk of complete failure without immediate intervention.',
    status: 'open',
    priority: 'critical',
    customerId: 'c3',
    customerName: 'Advanced Semiconductor Corp',
    assetId: 'a5',
    assetName: 'ZEISS GeminiSEM 560',
    createdAt: '2024-12-10T08:00:00Z',
    updatedAt: '2024-12-10T11:30:00Z',
    dueDate: '2024-12-13T17:00:00Z',
    tags: ['critical', 'FEG', 'SEM', 'emergency'],
    comments: [],
  },
  {
    id: 't3',
    title: 'Routine maintenance request - LSM 980',
    description: 'Request for scheduled 6-month preventive maintenance visit for the LSM 980 confocal system.',
    status: 'open',
    priority: 'low',
    customerId: 'c2',
    customerName: 'Stanford Research Institute',
    assetId: 'a4',
    assetName: 'ZEISS LSM 980 Confocal',
    createdAt: '2024-12-07T14:00:00Z',
    updatedAt: '2024-12-07T14:00:00Z',
    dueDate: '2025-01-15T17:00:00Z',
    tags: ['maintenance', 'scheduled', 'confocal'],
    comments: [],
  },
  {
    id: 't4',
    title: 'Vacuum system noise - SIGMA 500',
    description: 'Elevated acoustic noise from vacuum pump system. Customer concerned about performance impact on high-resolution imaging.',
    status: 'in_progress',
    priority: 'high',
    customerId: 'c3',
    customerName: 'Advanced Semiconductor Corp',
    assetId: 'a3',
    assetName: 'ZEISS SIGMA 500 SEM',
    assignedTo: 'eng2',
    assignedEngineer: 'Kenji Nakamura',
    createdAt: '2024-12-05T11:00:00Z',
    updatedAt: '2024-12-09T16:30:00Z',
    dueDate: '2024-12-25T17:00:00Z',
    tags: ['vacuum', 'SEM', 'hardware'],
    comments: [],
  },
  {
    id: 't5',
    title: 'OCT calibration verification',
    description: 'Annual calibration verification required for OCT 6000 as per hospital compliance requirements.',
    status: 'resolved',
    priority: 'medium',
    customerId: 'c1',
    customerName: 'MedTech Solutions GmbH',
    assetId: 'a2',
    assetName: 'ZEISS CIRRUS HD-OCT 6000',
    assignedTo: 'eng3',
    assignedEngineer: 'Anna Fischer',
    createdAt: '2024-11-20T09:00:00Z',
    updatedAt: '2024-12-02T15:00:00Z',
    resolvedAt: '2024-12-02T15:00:00Z',
    dueDate: '2024-12-15T17:00:00Z',
    tags: ['calibration', 'OCT', 'compliance'],
    comments: [],
  },
];

export const mockKnowledgeArticles: KnowledgeArticle[] = [
  {
    id: 'kb1',
    title: 'Troubleshooting Autofocus Issues in ZEISS Axio Observer Series',
    category: 'Microscopy',
    content: 'This guide covers systematic diagnosis and resolution of autofocus problems...',
    tags: ['autofocus', 'microscopy', 'troubleshooting'],
    views: 1243,
    helpful: 89,
    author: 'Technical Support Team',
    createdAt: '2023-06-15T09:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
    status: 'published',
  },
  {
    id: 'kb2',
    title: 'SEM Vacuum System Maintenance Guide',
    category: 'Semiconductor',
    content: 'Comprehensive maintenance procedures for SEM vacuum systems...',
    tags: ['SEM', 'vacuum', 'maintenance'],
    views: 892,
    helpful: 76,
    author: 'Field Service Engineering',
    createdAt: '2023-08-20T10:00:00Z',
    updatedAt: '2024-10-15T14:00:00Z',
    status: 'published',
  },
  {
    id: 'kb3',
    title: 'FEG Cathode Life Cycle and Replacement Procedures',
    category: 'Semiconductor',
    content: 'Field emission gun cathode maintenance, replacement timing, and procedures...',
    tags: ['FEG', 'cathode', 'SEM', 'replacement'],
    views: 654,
    helpful: 91,
    author: 'R&D Support Division',
    createdAt: '2022-12-01T09:00:00Z',
    updatedAt: '2024-09-20T11:00:00Z',
    status: 'published',
  },
  {
    id: 'kb4',
    title: 'OCT System Calibration and Compliance Procedures',
    category: 'Ophthalmology',
    content: 'Step-by-step calibration verification for CIRRUS and other OCT systems...',
    tags: ['OCT', 'calibration', 'ophthalmology', 'compliance'],
    views: 1087,
    helpful: 93,
    author: 'Clinical Applications Team',
    createdAt: '2023-03-10T10:00:00Z',
    updatedAt: '2024-11-05T09:00:00Z',
    status: 'published',
  },
  {
    id: 'kb5',
    title: 'Preventive Maintenance Schedule — ZEISS Confocal Systems',
    category: 'Research Systems',
    content: 'Recommended maintenance intervals and procedures for LSM series...',
    tags: ['confocal', 'LSM', 'maintenance', 'schedule'],
    views: 432,
    helpful: 88,
    author: 'Field Service Engineering',
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-11-20T10:00:00Z',
    status: 'published',
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  totalCustomers: 847,
  totalAssets: 3241,
  openTickets: 28,
  highRiskAssets: 14,
  aiAnalyses: 1847,
  maintenanceDue: 43,
  resolvedTickets: 312,
  avgRiskScore: 34,
};
